### PR TITLE
feat: add cmdutil package to provide utils for commands

### PR DESCRIPTION
**Pull request by hezhizhen**
## Summary

1. add cmdutil package
2. move command related functions to this package
3. tweak some error handling

### CODE REVIEW

**Review by LucilleH — APPROVED** [review]
Oh this looks much better!

**Comment by hezhizhen** [comment]
@ipince PTAL

**Comment by hezhizhen** [comment]
@savil PTAL

**Review by ipince — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
