### PR TITLE
[filegen] move plansdk.FlakePlan and plansdk.FlakeInput

### PR DESCRIPTION
**Pull request by savil**
## Summary

1. move `plansdk.FlakePlan` and `plansdk.FlakeInput` into `filegen` and make both internal to the package.
2. move `impl.FlakePlan()` to `filegen.newFlakePlan()` (note, it is internal)
3. move `impl.FlakeInputs()` to `filegen.flakeInputs()` (again, internal now)

### CODE REVIEW

**Comment by savil** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1187** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/1187" target="_blank">Graphite</a> 
    * **PR #1188** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/1188" target="_blank">Graphite</a> 
      * **PR #1189** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/1189" target="_blank">Graphite</a> 
        * **PR #1190** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/1190" target="_blank">Graphite</a> 
          * **PR #1191** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/1191" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jetpack-io/devbox/1191?utm_source=stack-comment).

**Review by LucilleH — COMMENTED** [review]
I realized I should've started from the bottom layer first instead of the top layer of PRs first. Now I'm getting the hang of it, I have some questions/concerns:

I feel like 80% of what we do is generating some script files. And some things can start with not generating any files in the earlier days, to generating files as it evolves.

So what goes in `filegen`? Is it supposed to be this big umbrella of all things that generates the files under `.devbox/gen`?

**Review by LucilleH — APPROVED** [review]
Approving to unblock

**Comment by savil** [comment]
Discussed offline with Lucille that I did originally envision `filegen` to be for files in .devbox/gen. We'll rename it to `devboxgen` , since filegen sounds too generic.

**Pull request merged**
