### PR TITLE
Add a new-project example

### PR DESCRIPTION
**Pull request by Lagoja**
## Summary

Adds a blank project that can be used with Devbox Cloud

## How was it tested?

Trivial

### CODE REVIEW

**Review by savil — APPROVED** [review]
thanks!

**Comment by LucilleH** [comment]
Wait we don't need template - we just need `devbox init` to power cloud

**Comment by hezhizhen** [comment]
> Wait we don't need this particular template - we just need `devbox init` to power cloud

Will `devbox init` create an `.envrc` file now?

**Comment by Lagoja** [comment]
Closing since we can use devbox directly to create a blank project

**Pull request closed without merging**
