### PR TITLE
[PHP] Add extension support and better version detection

### PR DESCRIPTION
**Pull request by mikeland86**
## Summary

Use composer.json to figure out if any extensions should be installed. Also, improved version detection (using `require` instead of `config`)

@loreto should we be using `systemPackages` instead of packages for languages?

## How was it tested?

```
devbox shell
php -m | grep mbstring 
```

### CODE REVIEW

**Comment by loreto** [comment]
Could you add a `testdata/` example that uses as many extensions as possible? 

Does `development.nix.tmpl` not need to change too?

Could you elaborate on:
> should we be using systemPackages instead of packages for languages?

**Comment by mikeland86** [comment]
> should we be using systemPackages instead of packages for languages?

in nix files "packages" are user packages. "systemPackages" belong to system. I guess since we are mostly doing single user setups it doesn't really matter

**Comment by mikeland86** [comment]
@loreto added tests, updated development.nix, and removed a few panics. PTAL

**Review by loreto — APPROVED** [review]
LGTM

**Pull request merged**
