### PR TITLE
chore: update descriptions for commands

### PR DESCRIPTION
**Pull request by hezhizhen**
## Summary

1. Use imperative sentences for command descriptions
2. Use exported functions for commands added to the root

### CODE REVIEW

**Review by ipince — APPROVED** [review]
Thanks!

**Comment by savil** [comment]
> Use exported functions for commands added to the root

why is this needed?

**Comment by hezhizhen** [comment]
> > Use exported functions for commands added to the root
> 
> why is this needed?

Not needed, because all functions are in the same package. But most of functions for commands added to the root are exported and sub-commands for these commands are unexported. So I think it's better to follow the pattern.

**Comment by savil** [comment]
Oh I see. I think that may be an oversight. In general, we should bias towards not visible _unless_ we intentionally want to export the function.

So, could we instead go the other way, and make the exported Command Functions be internal? I don't see a good reason for why they need to be exported.

**Comment by hezhizhen** [comment]
> Oh I see. I think that may be an oversight. In general, we should bias towards not visible _unless_ we intentionally want to export the function.
> 
> So, could we instead go the other way, and make the exported Command Functions be internal? I don't see a good reason for why they need to be exported.

Okay, I've changed all functions to be internal.

**Review by savil — APPROVED** [review]

**Comment by savil** [comment]
@hezhizhen thank you! for your PR and openness to modifying it.

**Pull request merged**
