### PR TITLE
Add revive linter and enable indent-error-flow rule

### PR DESCRIPTION
**Pull request by hezhizhen**
## Summary

1. Add `revive` linter to `.golangci.yml`
2. Enable `indent-error-flow` rule only for `revive`
3. Address related issues.

## How was it tested?

Linter.

### CODE REVIEW

**Comment by hezhizhen** [comment]
@ipince

**Comment by hezhizhen** [comment]
@savil Please take a look.

**Comment by savil** [comment]
@hezhizhen thanks! lgtm. Would you mind reverting the svg change?

**Comment by hezhizhen** [comment]
> @hezhizhen thanks! lgtm. Would you mind reverting the svg change?

Okay. And skip checking svg files?

**Comment by savil** [comment]
@hezhizhen I think that would make sense, unless there's some good reason you feel we should be checking svg files?

**Comment by hezhizhen** [comment]
> @hezhizhen I think that would make sense, unless there's some good reason you feel we should be checking svg files?

I have no idea about how svg files are generated... I'll skip them.

**Comment by hezhizhen** [comment]
@savil I rebased `main` and reverted changes in svg files. PTAL

**Review by savil — APPROVED** [review]

**Pull request merged**
