### PR TITLE
[wrappers] Always use system bash and sed in bin wrappers

### PR DESCRIPTION
**Pull request by mikeland73**
## Summary

This feels like the safest solution to https://github.com/jetpack-io/devbox/pull/1566#discussion_r1364318788

It also avoids creating bin wrappers for `bash` and `sed` which reduces risk and improves performance.

## How was it tested?

Used setup from https://github.com/jetpack-io/devbox/pull/1566

```
devbox shell
devbox add bash
hash -r
which bash # ensure I get profile bash instead of wrapped bash
```

### CODE REVIEW

**Comment by gcurtis** [comment]
Does this affect the user's devbox environment or just the wrappers? I think it would be surprising for users that explicitly want the coreutils version of sed. The macOS sed and the coreutils sed have some big differences in how they handle flags.

What if we do the following:

1. When devbox starts, check to see if `DEVBOX_SYSTEM_BASH` and `DEVBOX_SYSTEM_SED` are set. 2. If they aren't, find them in the PATH (before we modify it at all) and then set the env vars to their absolute paths.
3. When generating the wrappers, use those env var values. If for some reason the env vars are missing (for example, because the user unset them), assume `/bin/bash` and `/usr/bin/sed`.

**Comment by mikeland73** [comment]
@gcurtis sure I think that's a reasonable solution, but to be honest there's absolutely no benefit to generating wrappers for bash and sed. Why not avoid it?

**Comment by mikeland73** [comment]
FWIW, I'm pretty sure coreutils sed/bash works fine for our use case. But agree it's probably not great that the user can change which binaries we use. On the other hand if `sed` is not fully portable, we are not sure what binaries we're using either.

**Review by gcurtis — APPROVED** [review]
I might be misunderstanding. I thought that if we didn't wrap bash or sed then the user's devbox environment would end up using their OS's version of those program. If ~~it's~~ the user's devbox shell is still using the nix-installed bash and sed, then this looks good to me.

**Comment by mikeland73** [comment]
@gcurtis no, if we remove the wrapper, then we use binaries in the devbox nix profile.

**Pull request merged**
