### PR TITLE
Added search command with sorted results

### PR DESCRIPTION
**Pull request by mohsenari**
## Summary
Added `devbox search <package name>` command that searches nix store for packages that contain the `<package name>` in their name or description.

## How was it tested?
1. compile devbox
2. run `./devbox search openjdk` or any other package
3. see results

### CODE REVIEW

**Comment by savil** [comment]
dropping myself to clear my review queue, but feel free to add me back

**Comment by mikeland86** [comment]
@mohsenari sorry for delay on reviewing this. What did we decide in the demo? Should I take a look?

**Comment by mohsenari** [comment]
> @mohsenari sorry for delay on reviewing this. What did we decide in the demo? Should I take a look? 

@mikeland86 no worries. We decided to pause this until we figure out flakes copying the whole project to /nix/store

**Comment by mikeland86** [comment]
Removing from my queue until ready to review. Let me know!

**Pull request closed without merging**
