### PR TITLE
Clean up error handling and docs

### PR DESCRIPTION
**Pull request by hezhizhen**
## Summary

Move some methods of `Devbox` to `packages.go`. Simplify some error handling by the way.

Edit: #723 did the majority of the changes in this original PR. I left the additional error handling and docs changes in.

## How was it tested?

tests.

### CODE REVIEW

**Comment by hezhizhen** [comment]
@savil This PR fixes some TODOs of yours. PTAL

**Review by ipince — APPROVED** [review]

**Comment by ipince** [comment]
Thank you @hezhizhen !

If you can rebase or merge in `main` into your branch, then I can merge this PR.. Or, I can do it myself too later. Cheers

**Comment by ipince** [comment]
OK I did it myself, and edited the title/description after noticing that #723 already made most of the changes. Still, thank you for the contributions!

**Comment by savil** [comment]
thank you @hezhizhen!

**Pull request merged**
