### PR TITLE
[add package] retry with higher priority

### PR DESCRIPTION
**Pull request by savil**
## Summary

We want to re-try `nix profile install` with package conflicts by setting
a higher priority (lower priority number) for later packages.

## How was it tested?

using the github.com/jetpack-io/devbox-examples repo

before:
```
devbox-examples/development/ruby on  main [!?] on ☁️  (us-east-2) on ☁️  savil.srivastava@jetpack.io 💫 initial project sync
❯ devbox shell
Ensuring packages are installed.

Installing 2 packages: bundler, ruby_3_1.

[1/2] bundler
[1/2] bundler: Success
[2/2] ruby_3_1
	error: files '/nix/store/spgr12gk13af8flz7akbs18fj4whqss2-bundler-2.4.5/bin/bundle' and '/nix/store/l4wmx8lfn6hlcfmbyhmksm024f8hixm1-ruby-3.1.2/bin/bundle' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' or type 'nix profile install --help' if using 'nix profile' to find out howto change the priority of one of the conflicting packages (0 being the highest priority)
[2/2] ruby_3_1: Fail
Error: Command: /nix/var/nix/profiles/default/bin/nix profile install --profile /Users/savil/code/jetpack/devbox-examples/development/ruby/.devbox/nix/profile/default --impure nixpkgs/f80ac848e3d6f0c12c52758c0f25c10c97ca3b62#ruby_3_1 --extra-experimental-features ca-derivations --option experimental-features nix-command flakes --priority 5: exit status 1

Error: There was an internal error. Run with DEVBOX_DEBUG=1 for a detailed error message, and consider reporting it at https://github.com/jetpack-io/devbox/issues
```

after:
```
❯ devbox shell
Ensuring packages are installed.

Installing package: ruby_3_1.

[1/1] ruby_3_1
	error: files '/nix/store/spgr12gk13af8flz7akbs18fj4whqss2-bundler-2.4.5/bin/bundle' and '/nix/store/l4wmx8lfn6hlcfmbyhmksm024f8hixm1-ruby-3.1.2/bin/bundle' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' or type 'nix profile install --help' if using 'nix profile' to find out howto change the priority of one of the conflicting packages (0 being the highest priority)
[1/1] ruby_3_1: Fail
Warning: Detected a conflict installing ruby_3_1. Adding a higher priority and trying again.
[1/1] ruby_3_1
[1/1] ruby_3_1: Success
Starting a devbox shell...
(devbox)
```

### CODE REVIEW

**Comment by savil** [comment]
Current dependencies on/for this PR:
* main
  * **PR #736** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/736" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jetpack-io/devbox/736?utm_source=stack-comment).

**Comment by Lagoja** [comment]
Confirmed this worked, but 2 questions: 

1. Can we suppress or overwrite the error message? I thought my shell had failed at first
2. (Stretch) can we print something like 
```
Warning: Detected a conflict installing ruby_3_1. Adding a higher priority and trying again.
Warning: Using bundler-2.4.5/bin/bundle over ruby-3.1.2/bin/bundle. 
```

**Comment by savil** [comment]
@Lagoja 

1. should be doable
2. This is harder because I don't know how to find the provenance of bundler -> ruby package. Also to clarify behavior: in the example in the Test Plan we are installing ruby's bundler with higher priority than the bundler package itself.

**Comment by savil** [comment]
ugh, I think I should push the re-try logic inside `nix.ProfileInstall` so that all callers benefit from this.

**Comment by savil** [comment]
but....that leads to some edge-cases:
if two global-packages and one project-package have a conflict, then which one wins would depend on the order in which we install them, so we would need to ensure we _first_ install the global-packages and then the project-packages so that the project-packages _always_ win.

**Comment by savil** [comment]
closing in favor of https://github.com/jetpack-io/devbox/pull/738

**Pull request closed without merging**
