### PR TITLE
Simplify error handling

### PR DESCRIPTION
**Pull request by hezhizhen**
## Summary

Remove unnecessary `if` check and `err` variable declaration.

## How was it tested?

tests.

### CODE REVIEW

**Comment by savil** [comment]
thank you! I'm just going to sleep so can look in detail tomorrow at the PR.

Just wanted to give a head's up that the CICD errors don't seem to be caused by your changes. They just started occurring about an hour ago, and we need to figure out why.

**Comment by hezhizhen** [comment]
> thank you! I'm just going to sleep so can look in detail tomorrow at the PR.
> 
> Just wanted to give a head's up that the CICD errors don't seem to be caused by your changes. They just started occurring about an hour ago (same error being seen in other PRs), and we need to figure out why.

What a relief... I was trying to figure out why the tests failed. Thanks.

**Comment by ipince** [comment]
If you rebase on `main`, the CICD tests should (hopefully) pass!

**Comment by hezhizhen** [comment]
> If you rebase on `main`, the CICD tests should (hopefully) pass!

It works!

**Pull request merged**
