### PR TITLE
[CICD]: add spell chcker to GitHub action

### PR DESCRIPTION
**Pull request by hezhizhen**
## Summary

Add https://github.com/crate-ci/typos to GitHub action and fix existing typos.

### CODE REVIEW

**Review by ipince — APPROVED** [review]
Thanks!

**Comment by hezhizhen** [comment]
Not ready to merge it? @ipince

**Comment by savil** [comment]
@hezhizhen thanks! I think @ipince just forgot that you don't have merging privileges.

**Comment by mikeland86** [comment]
We should probably change this to not run on `main` branch and if possible also ignore some file types (e.g. `.svg`)

**Comment by savil** [comment]
@mikeland86 i'll send an update

**Pull request merged**
